version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: humanlink
      POSTGRES_USER: humanlink
      POSTGRES_PASSWORD: humanlink123
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U humanlink" ]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://humanlink:humanlink123@db:5432/humanlink
      - ENVIRONMENT=development
      - SECRET_KEY=django-insecure-woc6)6l2$$gz5rb4m8*t$#%xv2$knd)od*2o^afhcj8%o!t0&5
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
